version: "3.8"

name: yudao
services:
  nacos-service:
    container_name: nacos-service
    image: nacos/nacos-server:v2.2.0
    environment:
      - MODE=standalone
    volumes:
      - ./docker/nacos/logs:/home/nacos/logs
      - ./docker/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - 'mysql-service'
  xxljob-service:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxljob-service
    ports:
      - "9090:9090"
    volumes:
      - ./docker/xxl-job-admin/logs:/data/applogs
      - ./docker/xxl-job-admin/xxl-job/:/xxl-job
    environment:
      # 设置启动参数
      PARAMS: '
      --server.port=9090 
      --spring.datasource.url=jdbc:mysql://mysql-service:3306/xxl_job?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true 
      --spring.datasource.username=root 
      --spring.datasource.password=123456 
      --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver 
      --xxl.job.accessToken=default_token  
      --spring.datasource.type=com.zaxxer.hikari.HikariDataSource 
      --spring.datasource.hikari.minimum-idle=10 
      --spring.datasource.hikari.maximum-pool-size=30 
      --spring.datasource.hikari.auto-commit=true 
      --spring.datasource.hikari.idle-timeout=30000 
      --spring.datasource.hikari.pool-name=HikariCP 
      --spring.datasource.hikari.max-lifetime=900000 
      --spring.datasource.hikari.connection-timeout=10000 
      --spring.datasource.hikari.validation-timeout=1000 '

    depends_on:
      - 'mysql-service'

  rmqnamesrv-service:
    image: apache/rocketmq:5.1.0
    container_name: rmqnamesrv-service
    ports:
      - 9876:9876
    restart: always
    privileged: true
    volumes:
      - ./docker/rocketmq/nameserver/logs:/home/rocketmq/logs
      - ./docker/rocketmq/nameserver/bin/runserver.sh:/home/rocketmq/rocketmq-5.1.0/bin/runserver.sh
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    command: ["sh","mqnamesrv"]
  broker-service:
    image: apache/rocketmq:5.1.0
    container_name: rmqbroker-service
    ports:
      - 10909:10909
      - 10911:10911
    restart: always
    privileged: true
    volumes:
      - ./docker/rocketmq/broker/store:/home/rocketmq/logs
      - ./docker/rocketmq/broker/conf/broker.conf:/home/rocketmq/broker.conf
      - ./docker/rocketmq/broker/bin/runbroker.sh:/home/rocketmq/rocketmq-5.1.0/bin/runbroker.sh
    depends_on:
      - 'rmqnamesrv-service'
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    command: [ "sh","mqbroker","-c","/home/rocketmq/broker.conf" ]
  rmqdashboard-service:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard-service
    ports:
      - 9980:8080
    restart: always
    privileged: true
    depends_on:
      - 'rmqnamesrv-service'
    environment:
      - JAVA_OPTS= -Xmx256M -Xms256M -Xmn128M -Drocketmq.namesrv.addr=rmqnamesrv-service:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false

  mysql-service:
    image: mysql:8
    container_name: mysql-service

    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ruoyi-vue-pro}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - ./mysql:/var/lib/mysql/
      - ./sql/mysql:/docker-entrypoint-initdb.d





  redis-service:
    image: redis:6-alpine
    container_name: redis-service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data



  gateway-service:
    image: gateway
    container_name: gateway-service
    build:
      context: ./yudao-gateway/
    ports:
      - "48080:48080"
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev
 # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间
    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      - 'nacos-service'

  system-service:
    image: module-system-biz
    container_name: system-service
    ports:
      - "48081:48081"
    build:
      context: ./yudao-module-system/yudao-module-system-biz/
    environment:

      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:48081" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always
    depends_on:
      - 'mysql-service'
      - 'xxljob-service'

  infra-service:
    image: module-infra-biz
    container_name: infra-service
    ports:
      - "48082:48082"
    build:
      context: ./yudao-module-infra/yudao-module-infra-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:48082" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      system-service:
        condition: service_healthy

  report-service:
    image: module-report-biz
    container_name: report-service
    build:
      context: ./yudao-module-report/yudao-module-report-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy
  bpm-service:
    image: module-bpm-biz
    container_name: bpm-service
    build:
      context: ./yudao-module-bpm/yudao-module-bpm-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy
  pay-service:
    image: module-pay-biz
    container_name: pay-service
    build:
      context: ./yudao-module-pay/yudao-module-pay-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy
  mp-service:
    image: module-mp-biz
    container_name: mp-service
    build:
      context: ./yudao-module-mp/yudao-module-mp-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy

  trade-service:
    image: module-trade-biz
    container_name: trade-service
    build:
      context: ./yudao-module-trade/yudao-module-trade-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy


  product-service:
    image: module-product-biz
    container_name: product-service
    build:
      context: ./yudao-module-product/yudao-module-product-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy


  promotion-service:
    image: module-promotion-biz
    container_name: promotion-service
    build:
      context: ./yudao-module-promotion/yudao-module-promotion-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy

  member-service:
    image: module-member-biz
    container_name: member-service
    build:
      context: ./yudao-module-member/yudao-module-member-biz/
    environment:
      - TZ=Asia/Shanghai # 配置程序默认时区为上海（中国标准时间）
      - JAVA_TOOL_OPTIONS=-javaagent:/data/skywalking/skywalking-agent/skywalking-agent.jar # 配置skywalking
      - SW_AGENT_NAME=gateway
      - SW_AGENT_TRACE_IGNORE_PATH=Redisson/PING,/actuator/**,/admin/**
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=[YOUR_SKYWALKING_ADDR] # 请替换 your.skywalking.addr 为你的 skywalking 地址
      - SPRING_PROFILES_ACTIVE=dev # 指定程序运行环境
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos-service:8848 # 配置中心地址
      - SPRING_CLOUD_NACOS_CONFIG_NAMESPACE=dev # 命名空间
      - SPRING_CLOUD_NACOS_SERVER_ADDR=nacos-service:8848  # 注册中心地址
      - SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE=dev # 命名空间



    volumes:
      - ./docker/cloud/logs:/root/logs/
      - ./data/skywalking/skywalking-agent:/data/skywalking/skywalking-agent
    restart: always

    depends_on:
      infra-service:
        condition: service_healthy

  admin-service:
    container_name: admin-service
    build:
      context: ./yudao-ui-admin
      args:
        NODE_ENV:
          ENV=${NODE_ENV:-production}
          PUBLIC_PATH=${PUBLIC_PATH:-/}
          VUE_APP_TITLE=${VUE_APP_TITLE:-芋道管理系统}
          VUE_APP_BASE_API=${VUE_APP_BASE_API:-/prod-api}
          VUE_APP_APP_NAME=${VUE_APP_APP_NAME:-/}
          VUE_APP_TENANT_ENABLE=${VUE_APP_TENANT_ENABLE:-true}
          VUE_APP_CAPTCHA_ENABLE=${VUE_APP_CAPTCHA_ENABLE:-true}
          VUE_APP_DOC_ENABLE=${VUE_APP_DOC_ENABLE:-true}
          VUE_APP_BAIDU_CODE=${VUE_APP_BAIDU_CODE:-fadc1bd5db1a1d6f581df60a1807f8ab}
    image: admin
    restart: unless-stopped
    ports:
      - "8080:80"
